version: '3.7'

volumes:
  gems:

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    links:
      - db:dbhost
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - gems:/usr/local/bundle
      - .:/opt/app:cached
    environment:
      TIME_ZONE: 'Brasilia'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
